import { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import HydrationFix from "@/components/HydrationFix";
import { I18nProvider } from "@/components/I18nProvider";
import StructuredData from "@/components/StructuredData";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import { TOOLS } from "@/lib/tools";

/** The 17 converters plus the formatter on `/`. */
const TOOL_COUNT = TOOLS.length + 1;

// Under 160 characters so Google shows the whole thing. The previous copy ran to
// 165 and spent its last clause on "Professional developer tools for JSON
// processing", which is what everyone says and tells a reader nothing.
const SITE_DESCRIPTION = `Format, validate, minify, and convert JSON in your browser. ${TOOL_COUNT} tools including YAML, XML, CSV, and type generation. Nothing uploads.`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    // The visible brand is JSON1, so the suffix matches it. Pages that already
    // carry their own brand suffix must use `title.absolute`, or the template
    // appends a second one — 25 wiki pages shipped as
    // "… | JSON Tools | JSON Tools" before this was noticed.
    default: "JSON1 — Free Online JSON Formatter, Validator & Converter",
    template: "%s | JSON1",
  },
  description:
    SITE_DESCRIPTION,
  keywords: [
    "json formatter",
    "json validator",
    "json converter",
    "json minifier",
    "json to xml",
    "json to csv",
    "online json tools",
    "json beautifier",
    "json parser",
    "format json online",
    "validate json",
    "json viewer",
    "json editor",
    "developer tools",
  ],
  authors: [{ name: "JSON1" }],
  creator: "JSON1",
  publisher: "JSON1",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://www.json.how"),
  // No `alternates` here on purpose.
  //
  // `canonical` is inherited by every route that does not set its own, so a
  // root-level `canonical: "/"` made 24 wiki pages and /404/ declare the
  // homepage as their canonical URL — telling Google to drop them from the
  // index. Each page owns its canonical instead; `metadataBase` above lets
  // them use a relative path.
  //
  // There is also no `languages` block. The four locales share one URL and are
  // applied client-side from the zustand store, so there are no per-locale URLs
  // to point hreflang at. The previous `/?lang=zh` targets were never read by
  // any code, and Next resolved all four to the same absolute URL — four
  // hreflang tags for one page, which violates the spec. Only the wiki has real
  // per-locale routes, and those pages declare their own hreflang.
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://www.json.how",
    title: "JSON1 — Free Online JSON Formatter, Validator & Converter",
    description:
      SITE_DESCRIPTION,
    siteName: "JSON1",
    // Inherited by every route, so a page without its own image still gets a
    // social card instead of a blank one. Generated by `pnpm og`.
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "JSON1 — JSON formatter, validator, and converters that run in your browser",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "JSON1 — Free Online JSON Formatter, Validator & Converter",
    description:
      SITE_DESCRIPTION,
    images: ["/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // `verification` intentionally omitted. It previously shipped the literal
  // strings "your-google-verification-code" etc., which render as real meta
  // tags and verify nothing. Add it back with actual codes when the property is
  // claimed in Search Console / Bing Webmaster Tools.
};

const GA_ID = process.env.NEXT_PUBLIC_GA_ID || "G-6FX1CYKSLV";
const IS_PROD = process.env.NODE_ENV === "production";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="JSON1" />
        {/* Removed missing apple-touch-icon to avoid 404; Next.js serves app/favicon.* automatically */}
        {/* Matches the cobalt token, not Tailwind's default blue. */}
        <meta name="theme-color" content="#1261ff" />
        {/* Google AdSense */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4969757168101127"
          crossOrigin="anonymous"
        />
        {IS_PROD && GA_ID ? (
          <>
            <Script
              id="gtag-lib"
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
              strategy="afterInteractive"
            />
            <Script id="gtag-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                window.gtag = window.gtag || gtag;
                gtag('js', new Date());
                gtag('config', '${GA_ID}', { send_page_view: false });
              `}
            </Script>
          </>
        ) : null}
        {IS_PROD ? (
          <Script id="ms-clarity" strategy="afterInteractive">
            {`
              (function(c,l,a,r,i,t,y){
                  c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                  t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                  y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "tokl9x7rbv");
            `}
          </Script>
        ) : null}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-[#f7f7f4] text-[#141414] antialiased`}
        suppressHydrationWarning={true}
      >
        <I18nProvider>
          <HydrationFix>
            <StructuredData />
            {/* GoogleAnalytics reads useSearchParams, which has no value during
                a static export, so it must sit behind its own boundary or it
                would opt every page out of prerendering. */}
            {IS_PROD && GA_ID ? (
              <Suspense fallback={null}>
                <GoogleAnalytics />
              </Suspense>
            ) : null}
            {children}
          </HydrationFix>
        </I18nProvider>
      </body>
    </html>
  );
}
